# -*- coding: utf-8 -*-
"""Whatsapp_Chat_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WWNrv3zlr3D-DA0bl8aaZMbPpLRbiwSs
"""

# =========================================================
# ADVANCED WHATSAPP CHAT ANALYSIS
# WITH:
# - SENTIMENT ANALYSIS
# - TOXIC MESSAGE DETECTION
# - WORD CLOUD
# - HEATMAP
# - USER ANALYSIS
# =========================================================

# =========================================================
# INSTALL REQUIRED LIBRARIES
# =========================================================

!pip install emoji regex wordcloud seaborn textblob detoxify --quiet

# =========================================================
# IMPORT LIBRARIES
# =========================================================

from google.colab import files
import pandas as pd
import numpy as np
import re
import regex
import emoji
import matplotlib.pyplot as plt
import seaborn as sns

from wordcloud import WordCloud, STOPWORDS
from collections import Counter
from textblob import TextBlob
from detoxify import Detoxify

# =========================================================
# UPLOAD WHATSAPP CHAT FILE
# =========================================================

uploaded = files.upload()

filename = list(uploaded.keys())[0]

print("Uploaded File:", filename)

# =========================================================
# FUNCTIONS
# =========================================================

# Detect start of message
def startsWithDateAndTime(s):

    pattern = r'^(\d{1,2})/(\d{1,2})/(\d{2,4}), (\d{1,2}):(\d{2})\s?(AM|PM|am|pm)? -'

    return re.match(pattern, s) is not None

# Extract message information
def getDataPoint(line):

    splitLine = line.split(' - ')

    dateTime = splitLine[0]

    message = " - ".join(splitLine[1:])

    date, time = dateTime.split(', ')

    if ': ' in message:
        author, message = message.split(': ', 1)
    else:
        author = "Group Notification"

    return date, time, author, message

# Extract emojis
def extract_emojis(text):

    emoji_list = []

    data = regex.findall(r'\X', str(text))

    for word in data:

        if any(char in emoji.EMOJI_DATA for char in word):
            emoji_list.append(word)

    return emoji_list

# Sentiment Analysis
def get_sentiment(text):

    analysis = TextBlob(str(text))

    polarity = analysis.sentiment.polarity

    if polarity > 0:
        return "Positive"

    elif polarity < 0:
        return "Negative"

    else:
        return "Neutral"

# Toxicity Detection
toxicity_model = Detoxify('original')

def detect_toxicity(text):

    try:

        result = toxicity_model.predict(str(text))

        toxicity_score = result['toxicity']

        if toxicity_score >= 0.5:
            return "Toxic"

        else:
            return "Non-Toxic"

    except:

        return "Non-Toxic"

# =========================================================
# PARSE WHATSAPP CHAT
# =========================================================

parsedData = []

messageBuffer = []

date, time, author = None, None, None

with open(filename, encoding="utf-8") as fp:

    fp.readline()

    while True:

        line = fp.readline()

        if not line:
            break

        line = line.strip()

        if startsWithDateAndTime(line):

            if len(messageBuffer) > 0:

                parsedData.append([
                    date,
                    time,
                    author,
                    ' '.join(messageBuffer)
                ])

            messageBuffer.clear()

            date, time, author, message = getDataPoint(line)

            messageBuffer.append(message)

        else:

            messageBuffer.append(line)

# Add final message
if len(messageBuffer) > 0:

    parsedData.append([
        date,
        time,
        author,
        ' '.join(messageBuffer)
    ])

# =========================================================
# CREATE DATAFRAME
# =========================================================

df = pd.DataFrame(
    parsedData,
    columns=['Date', 'Time', 'Author', 'Message']
)

# Convert date
df["Date"] = pd.to_datetime(
    df["Date"],
    dayfirst=True,
    errors='coerce'
)

# =========================================================
# BASIC ANALYSIS
# =========================================================

total_messages = df.shape[0]

media_messages = df[
    df['Message'] == '<Media omitted>'
].shape[0]

# URL Count
URLPATTERN = r'(https?://\S+)'

df['urlcount'] = df["Message"].apply(
    lambda x: re.findall(URLPATTERN, str(x))
).str.len()

links = df['urlcount'].sum()

# Emoji Count
df["emoji"] = df["Message"].astype(str).apply(extract_emojis)

emojis = sum(df['emoji'].str.len())

# =========================================================
# SENTIMENT ANALYSIS
# =========================================================

print("Running Sentiment Analysis...")

df['Sentiment'] = df['Message'].apply(get_sentiment)

# =========================================================
# TOXIC MESSAGE DETECTION
# =========================================================

print("Running Toxic Message Detection...")

df['Toxicity'] = df['Message'].apply(detect_toxicity)

# =========================================================
# PRINT SUMMARY
# =========================================================

print("\n========== WHATSAPP CHAT ANALYSIS ==========\n")

print("Total Messages :", total_messages)

print("Media Shared   :", media_messages)

print("Emojis Used    :", emojis)

print("Links Shared   :", links)

print("\n===========================================\n")

# =========================================================
# MESSAGE STATISTICS
# =========================================================

media_messages_df = df[df['Message'] == '<Media omitted>']

messages_df = df.drop(media_messages_df.index)

messages_df['Letter_Count'] = messages_df['Message'].apply(
    lambda s: len(str(s))
)

messages_df['Word_Count'] = messages_df['Message'].apply(
    lambda s: len(str(s).split())
)

messages_df['MessageCount'] = 1

# =========================================================
# USER ANALYSIS
# =========================================================

members = messages_df['Author'].unique()

print("\n========== USER ANALYSIS ==========\n")

for name in members:

    user_msgs = messages_df[
        messages_df["Author"] == name
    ]

    print(f"\nUser : {name}")

    print("Messages Sent :",
          user_msgs.shape[0])

    words_per_msg = (
        np.sum(user_msgs['Word_Count'])
        / user_msgs.shape[0]
    ) if user_msgs.shape[0] > 0 else 0

    print("Words per Message :",
          round(words_per_msg, 2))

    media_count = media_messages_df[
        media_messages_df["Author"] == name
    ].shape[0]

    print("Media Shared :",
          media_count)

    emoji_count = sum(
        user_msgs["emoji"].str.len()
    )

    print("Emojis Sent :",
          emoji_count)

    link_count = sum(
        user_msgs["urlcount"]
    )

    print("Links Shared :",
          link_count)

    print("-" * 40)

# =========================================================
# SENTIMENT ANALYSIS
# =========================================================

print("\n========== SENTIMENT ANALYSIS ==========\n")

sentiment_counts = messages_df['Sentiment'].value_counts()

print(sentiment_counts)

# =========================================================
# SENTIMENT BAR GRAPH
# =========================================================

plt.figure(figsize=(7,5))

sentiment_counts.plot(kind='bar')

plt.title("Sentiment Analysis")

plt.xlabel("Sentiment")

plt.ylabel("Count")

plt.grid()

plt.show()

# =========================================================
# USER-WISE SENTIMENT HEATMAP
# =========================================================

user_sentiment = pd.crosstab(
    messages_df['Author'],
    messages_df['Sentiment']
)

plt.figure(figsize=(10,6))

sns.heatmap(
    user_sentiment,
    annot=True,
    cmap="coolwarm",
    fmt='d'
)

plt.title("User-wise Sentiment Heatmap")

plt.show()

# =========================================================
# TOXICITY ANALYSIS
# =========================================================

print("\n========== TOXIC MESSAGE ANALYSIS ==========\n")

toxicity_counts = messages_df['Toxicity'].value_counts()

print(toxicity_counts)

# =========================================================
# TOXICITY BAR GRAPH
# =========================================================

plt.figure(figsize=(7,5))

toxicity_counts.plot(kind='bar')

plt.title("Toxic vs Non-Toxic Messages")

plt.xlabel("Category")

plt.ylabel("Count")

plt.grid()

plt.show()

# =========================================================
# USER-WISE TOXICITY ANALYSIS
# =========================================================

user_toxicity = pd.crosstab(
    messages_df['Author'],
    messages_df['Toxicity']
)

plt.figure(figsize=(10,6))

sns.heatmap(
    user_toxicity,
    annot=True,
    cmap="Reds",
    fmt='d'
)

plt.title("User-wise Toxicity Heatmap")

plt.show()

# =========================================================
# MOST TOXIC USERS
# =========================================================

toxic_msgs = messages_df[
    messages_df['Toxicity'] == 'Toxic'
]

print("\n========== MOST TOXIC USERS ==========\n")

toxic_users = toxic_msgs['Author'].value_counts()

print(toxic_users)

# =========================================================
# TOXIC MESSAGE PERCENTAGE
# =========================================================

if 'Toxic' in toxicity_counts:

    toxicity_percentage = (
        toxicity_counts['Toxic']
        / len(messages_df)
    ) * 100

else:

    toxicity_percentage = 0

print(
    "\nToxic Message Percentage:",
    round(toxicity_percentage, 2),
    "%"
)

# =========================================================
# SHOW MOST TOXIC MESSAGES
# =========================================================

print("\n========== SAMPLE TOXIC MESSAGES ==========\n")

print(
    toxic_msgs[['Author', 'Message']].head(10)
)

# =========================================================
# TOP EMOJIS
# =========================================================

total_emojis_list = list(
    [a for b in messages_df.emoji for a in b]
)

emoji_dict = dict(
    Counter(total_emojis_list)
)

emoji_dict = sorted(
    emoji_dict.items(),
    key=lambda x: x[1],
    reverse=True
)

print("\n========== TOP EMOJIS ==========\n")

for i in emoji_dict[:10]:

    print(i)

# =========================================================
# WORD CLOUD
# =========================================================

text = " ".join(
    review for review in messages_df["Message"].astype(str)
)

stopwords = set(STOPWORDS)

wordcloud = WordCloud(
    stopwords=stopwords,
    background_color="white",
    width=1000,
    height=500
).generate(text)

plt.figure(figsize=(15, 7))

plt.imshow(wordcloud, interpolation="bilinear")

plt.axis("off")

plt.title("Most Frequent Words in Chat")

plt.show()

# =========================================================
# USER WORD CLOUDS
# =========================================================

participants = messages_df['Author'].unique()

for name in participants:

    user_df = messages_df[
        messages_df['Author'] == name
    ]

    if user_df.empty:
        continue

    text = " ".join(
        msg for msg in user_df["Message"].astype(str)
    )

    wordcloud = WordCloud(
        stopwords=stopwords,
        background_color="white",
        width=1000,
        height=500
    ).generate(text)

    plt.figure(figsize=(12, 5))

    plt.imshow(
        wordcloud,
        interpolation='bilinear'
    )

    plt.axis("off")

    plt.title(f'Most Used Words by {name}')

    plt.show()

# =========================================================
# HEATMAP ANALYSIS
# =========================================================

messages_df['Day'] = messages_df['Date'].dt.day_name()

messages_df['Hour'] = messages_df['Time'].apply(
    lambda x: int(str(x).split(':')[0])
    if ':' in str(x) else 0
)

heatmap_data = messages_df.pivot_table(
    index='Day',
    columns='Hour',
    values='MessageCount',
    aggfunc='sum'
).fillna(0)

ordered_days = [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday'
]

heatmap_data = heatmap_data.reindex(
    ordered_days
)

plt.figure(figsize=(15, 6))

sns.heatmap(
    heatmap_data,
    cmap="YlGnBu",
    linewidths=0.3,
    linecolor='gray',
    annot=True,
    fmt='.0f'
)

plt.title(
    'WhatsApp Message Activity Heatmap'
)

plt.xlabel('Hour of Day')

plt.ylabel('Day of Week')

plt.tight_layout()

plt.show()

# =========================================================
# MOST ACTIVE USERS
# =========================================================

user_counts = messages_df['Author'].value_counts()

plt.figure(figsize=(10, 5))

user_counts.plot(kind='bar')

plt.title("Most Active Users")

plt.xlabel("Users")

plt.ylabel("Message Count")

plt.xticks(rotation=45)

plt.grid()

plt.show()

# =========================================================
# DAILY MESSAGE TIMELINE
# =========================================================

timeline = messages_df.groupby('Date').count()['Message']

plt.figure(figsize=(15, 5))

timeline.plot()

plt.title("Daily Message Timeline")

plt.xlabel("Date")

plt.ylabel("Messages")

plt.grid()

plt.show()

# =========================================================
# DAILY SENTIMENT TREND
# =========================================================

daily_sentiment = pd.crosstab(
    messages_df['Date'],
    messages_df['Sentiment']
)

daily_sentiment.plot(figsize=(15,5))

plt.title("Daily Sentiment Trend")

plt.xlabel("Date")

plt.ylabel("Messages")

plt.grid()

plt.show()

# =========================================================
# EXPORT CLEANED DATA
# =========================================================

df.to_csv(
    "advanced_whatsapp_chat_analysis.csv",
    index=False
)

print("\nCSV File Saved Successfully")